### ISSUE TITLE
P1: "Done" on Patient Details goes to Search instead of Home

### ISSUE THREAD

**Issue by dburka** [resolvetosavelives/redapp#142]
When you search for a patient, then add a BP, then hit "Done" on the green button at the bottom of the patient details screen, the user is taken back to search.

Note: When you add a new patient, the flow is correct and the user is returned to the home screen.

Tested on production app.

**Comment by pratul** [comment]
Fixed by 6c30fd2b79ad32f5ba6316082d1570ef10a75cab
