### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by dvenkatr** [resolvetosavelives/redapp#20]
- [x] Canary test to ensure sanity of the test rig
- [x] Ensure downloadable APKs are being generated
- [x] Ensure that individual artifacts can be downloaded, and not a combined compressed artifact
- [ ] Pay for Bitrise and ask them for an "open source discount" or something

**Comment by pratul** [comment]
- [ ] Canary test to ensure the app starts up on an emulator
- [ ] Ensure downloadable APKs are being generated

**Comment by pratul** [comment]
@timcheadle you will have to talk to bitrise.io and figure out if they will give us a special plan for being an open source project. If they won't, you will have to setup payment on bitrise -- our trial ends in 7 days.

**Comment by timcheadle** [comment]
I think this is all done.
