### ISSUE TITLE
Setup Domain, SSL Certificates for simple.org.

### ISSUE THREAD

**Issue by ssrihari** [resolvetosavelives/redapp#75]
- [x] Buy Domain
- [x] Buy SSL Certs
- [x] Add subdomain for staging
- [x] Add subdomain for admin?
- [x] make ansible use SSL certs in nginx config
- [ ] change capistrano to use simple.org

**Comment by timcheadle** [comment]
I can't complete this until @govindkrjoshi adds feature flags around OTP/login. Right now we can't deploy master, which means I can't test the Capistrano config changes.
