### ISSUE TITLE
Add privacy policy for play store

### ISSUE THREAD

**Issue by ssrihari** [resolvetosavelives/redapp#95]
Draft is here: https://github.com/resolvetosavelives/redapp/blob/add-privacy-policy/privacy-policy.md

We need to edit this, and merge into master. If there is a better place for the privacy policy (ex: website), we should put it there.

We can't release apps on the play store without a privacy policy.

**Comment by dburka** [comment]
The privacy policy is up on the simple.org. https://www.simple.org/privacy/

**Comment by ssrihari** [comment]
@dburka This is updated on the play store now. Thanks!
